### ISSUE TITLE
Loving this package. Quick question about byValues vs byValue.

### ISSUE THREAD

**Issue by GollyJer** [cosimochellini/sort-es#1]
Hi. This is so easy to use, fast, and creates readable code. I'm really enjoying it.

Is there a difference/benefit to one of these approaches?

```javascript
const weightsAsc = healthData.weights.sort(byValues({ created_at: byDate() }));
```
vs
```javascript
const weightsAsc = healthData.weights.sort(byValue((weight) => weight.created_at, byDate()));
```

Why would I go with the second when the first is more succinct? Thanks!

**Comment by cosimochellini** [comment]
Hi! thanks for the question! 
I state that both solutions lead to the **same result**.
By the way, as I thought the library, **byValue** was used to specify that you were going to order for **one and only one object property**.
Another useful thing about byValue is to be able to sort by nested properties or even to adjust an object property.
Examples: 
```javascript
const weightsAsc = healthData.weights.sort(byValue(
         (weight) => weight.created_at.nestedProp, byDate())
);

//which combines well with Optional chaining

const weightsAsc = healthData.weights.sort(byValue(
         (weight) => weight?.some?.property ?? 0, byNumber())
);

//and also with objects that have a method to invoke
const weightsAsc = healthData.weights.sort(byValue(
         (weight) => weight.calculateWeight(), byNumber())
);

```

I hope I have clarified you: D

**Comment by GollyJer** [comment]
Wow. Really cool. I love it even more... thanks for the clarification and examples! 👍
