### ISSUE TITLE
byDate doesn't handle nullable

### ISSUE THREAD

**Issue by Munter** [cosimochellini/sort-es#12]
When sorting `byDate` on a column that might contain `null`, the `byDate` function throws:

```
// releasedAt is a nullable ISO date string: string | null 
byValues([
  [(i) => i.releasedAt as string, byDate({ nullable: true, desc })],
])

// Throws: TypeError: Cannot read properties of null (reading 'getTime')
```

**Comment by cosimochellini** [comment]
Hi @Munter , you're correct! the byDate function does not handle the nullable option properly, I've released the version`1.6.13` that should support it.

Please update and try again, thanks for the report!

PS, thanks also to open the other problems in separate issues, I'll look into them in the next few days!
