### ISSUE TITLE
byNumber()(Infinity, Infinity) returns NaN

### ISSUE THREAD

**Issue by johnw42** [cosimochellini/sort-es#13]
Comparing subtracting Infinity or -Infinity from itself produces NaN, which causes byNumber to return NaN. This isn't a problem for sorting, because Array.prototype.sort treats NaN as 0, but it probably violates user expectations. It can be fixed by adding "|| 0" after the subtractions in byNumber.

**Comment by cosimochellini** [comment]
hey, sorry for the late reply!

Make sense, I'll fix this behavior as soon as possible! 💪

**Comment by cosimochellini** [comment]
Hey @johnw42 I've released the `v1.6.16` with the fix! 

Thanks for having pointed it out!
